--- 
- name: Create container for nginx
  docker_container:
    name: "nginx-b"
    ports:
    - "8888:80"
    state: started
    interactive: yes
    image: centos
  become: yes
- name: Update
  shell: docker exec nginx-b yum update -y 
- name: Install epel
  shell: docker exec nginx-b yum install -y epel-release
- name: Install nginx
  shell: docker exec nginx-b yum install -y nginx
- name: Create template
  template: src=default.j2 dest=~/nginx.conf
- name: Stop nginx
  service: 
    name: nginx
    state: stopped
- name: Copying 
  command: docker cp ~/nginx.conf nginx-b:/etc/nginx/nginx.conf
  block:
    - name: Try to start nginx
      command: docker exec nginx-b nginx
    - name: Wait for nginx (30 sec)
      pause:
        seconds: 30
  rescue:
    - name: Restart nginx
      command: docker exec nginx-b nginx -s reload
- name: Check nginx
  shell: curl 172.17.0.10
