--- 
- name: Create container for nginx
  docker_container:
    name: "nginx-b"
    ports:
    - "8888:80"
    state: started
    interactive: yes
    image: centos
  become: yes
- name: Update and install epel
  shell: docker exec nginx-b yum update -y && yum install -y epel-release
  become: yes
- name: Install nginx
  shell: docker exec nginx-b 'yum install -y nginx'
  become: yes
- name: Create template
  template: src=default.j2 dest=~/nginx.conf
- name: Copying 
  shell: docker cp ~/nginx.conf nginx-b:/etc/nginx/nginx.conf
- name: Restarting service nginx
  shell: docker exec nginx-b 'nginx -r'
  become: yes
- name: Check nginx
  shell: curl 172.17.0.10
