--- 
- name: Create container for Nginx
  docker_container:
    name: "Nginx-b"
    ports:
    - "8888:80"
    interactive: yes
    image: ubuntu
    entrypoint: apt update -y && apt install nginx -y && service start nginx
- name: Update packages
  shell: ssh jenkins@172.17.0.7 sudo apt update -y
- name: Install Nginx
  shell: ssh jenkins@172.17.0.7 sudo apt install nginx -y
- name: Check Nginx
  shell: curl 172.17.0.10:8888
