--- 
- name: Create container for Nginx
  docker_container:
    name: "Nginx-b"
    ports:
    - "8888:80"
    command: apt-get update -y && apt-get install nginx && service nginx start
    interactive: yes
    image: ubuntu
  become: yes
- name: Copying template
  template: src=default.j2 dest=~/DEFAULT
  become: yes
- name: Restarting service Nginx
  shell: docker exec Nginx-b sudo service nginx restart
  become: yes
- name: Check Nginx
  shell: curl 172.17.0.10
