--- 
- name: Create container for nginx
  docker_container:
    name: "nginx-b"
    ports:
    - "8888:80"
    state: started
    interactive: yes
    image: centos
    recreate: yes 
  become: yes
- name: Update
  shell: docker exec nginx-b yum update -y 
- name: Install epel
  shell: docker exec nginx-b yum install -y epel-release
- name: Install nginx
  shell: docker exec nginx-b yum install -y nginx
- name: Create template
  template: src=default.j2 dest=~/nginx.conf
- name: Copying 
  shell: docker cp ~/nginx.conf nginx-b:/etc/nginx/nginx.conf
- name: Check configuration
  shell: docker exec nginx-b 'nginx'
- name: Check nginx
  shell: curl 172.17.0.10
