--- 
- name: Create container for Nginx
  docker_container:
    name: "Nginx-b"
    ports:
    - "8888:80"
    interactive: yes
    image: ubuntu
  become: yes
- name: Update packages
  shell: sudo docker exec Nginx-b sudo apt update -y
  become: yes
- name: Install Nginx
  shell: docker exec Nginx-b sudo apt install nginx -y && service nginx start
  become: yes
- name: Copying template
  template: src=default.j2 dest=~/DEFAULT
  become: yes
- name: Restarting service Nginx
  shell: docker exec Nginx-b sudo service nginx restart
  become: yes
- name: Check Nginx
  shell: curl 172.17.0.10
