--- 
- name: Create container for Nginx
  docker_container:
    name: "Nginx-b"
    ports:
    - "8888:80"
    state: started
    interactive: yes
    image: centos
  become: yes
- name: Update and install Nginx
  shell: docker exec -i Nginx-b yum update -y && yum install -y epel-release nginx && service nginx start
- name: Create template
  template: src=default.j2 dest=~/nginx.conf
  become: yes
- name: Copying 
  shell: docker cp ~/nginx.conf Nginx-b:/etc/nginx/nginx.conf
- name: Restarting service Nginx
  shell: docker exec Nginx-b service nginx restart
  become: yes
- name: Check Nginx
  shell: curl 172.17.0.10
