--- 
- name: Create container for Nginx
  docker_container:
    name: "Nginx-b"
    ports:
    - "8888:80"
    command: apt-get update -y
    interactive: yes
    image: ubuntu
  become: yes
- name: Create template
  template: src=default.j2 dest=~/nginx.conf
  become: yes
- name: Copying 
  shell: docker cp ~/nginx.conf Nginx-b:/etc/nginx/nginx.conf
- name: Restarting service Nginx
  shell: docker exec Nginx-b sudo service nginx restart
  become: yes
- name: Check Nginx
  shell: curl 172.17.0.10
