--- 
- name: Create container for Nginx
  docker_container:
    name: "Nginx-b"
    ports:
    - "8888:80"
    interactive: yes
    image: ubuntu
- name: Update packages
  shell: docker exec Nginx-b apt update -y
- name: Install Nginx
  shell: docker exec Nginx-b apt install nginx -y
- name: Template
  template: src=default.j2 dest=~/DEFAULT
- name: Check Nginx
  shell: curl 172.17.0.10
