---
- name: ping
  ping:
- name: Create docker containers
  docker_container:
    name: "web-app_ans{{ item }}"
    ports:
     - "50{{ item }}0:5000"
    interactive: yes 
    image: 112212/stud-exam:web-app_latest
  become: yes
  with_sequence: count=3
- name: Check web app 1
  get_url:
    url: http://{{ web_ip1 }}:5000
    dest: .
- name: Check web app 2
  get_url:
    url: http://{{ web_ip2 }}:5000
    dest: .
- name: Check web app 3
  get_url:
    url: http://{{ web_ip3 }}:5000
    dest: .




    

