---
- name: Install pip
  shell: apt install python-pip -y
  become: yes
- name: Install docker-py
  shell: pip install docker-py
  become: yes
- name: Install Docker
  shell: cd / && sudo sh get-docker.sh
- name: Check Docker
  shell: docker -v
     
