---
- name: Install pip
  shell: apt-get install python-pip -y
  become_user: root
- name: Install docker-py
  shell: sudo pip install docker-py
- name: Install Docker
  shell: cd / && sudo sh get-docker.sh
- name: Check Docker
  shell: docker -v
     
