---
- name: Install pip
   apt:
     name: "{{ packages }}"
  vars:
    packages:
    - python-pip
    - docker
    - docker-py
  become: yes
- name: Permit docker sock
  shell: chmod 770 /var/run/docker.sock
  become: yes
- name: Check Docker
  shell: docker -v
