---
- name: Install pip
  shell: apt install python-pip -y
  become: yes
- name: Install docker-py
  shell: pip install docker-py
  become: yes
- name: Check if apache is installed
  command: dpkg-query -l docker
  ignore_errors: True
  register: deb_check
- name: Install Docker
  shell: cd / && sudo sh get-docker.sh
  when: deb_check.stderr.find('no packages found') != -1
- name: Check Docker
  shell: docker -v
