---
- name: Install pip
  shell: apt install python-pip -y
  become: yes
- name: Install docker-py
  shell: pip install docker-py
  become: yes
- name: Install docker
  apt:
    pkg: docker
    state: latest
  become: yes
- name: Check Docker
  shell: docker -v
